# ============================================================================
# Filters pour détection de changements
# ============================================================================
# Détecte quels composants ont changé pour ne rebuild que le nécessaire

chaincode:
  - 'chaincode-java/**'
  - 'Dockerfile.deployer'

api:
  - 'api/**'
  - 'api/Dockerfile'

infrastructure:
  - 'docker-compose-production.yml'
  - 'network/**'
  - '.github/workflows/**'
